name: Sync with Gosh

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Sync
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
          GOSH_URL: gosh://0:e87874f4a9e46f9f16e0c09c824204836b31d60b16db050a8c7fe329bb43d120/awnion/gosh-sync
        run: |
          echo "$CONFIG_JSON" >config.json
          docker pull ghcr.io/awnion/git-remote-gosh
          cat <<EOF >gosh_sync.sh
          #!/bin/bash
          set -xe

          env
          git fetch -a
          git pull
          git status
          git remote -v
          git remote add gosh $GOSH_URL
          git remote -v
          git switch -C github_${{ github.ref_name }}
          git status
          ls -lA
          RUST_BACKTRACE=1 git push -v gosh
          EOF

          cat gosh_sync.sh

          docker run --rm -v "$(pwd)":/workdir -v "$(pwd)"/config.json:/root/.gosh/config.json:ro ghcr.io/awnion/git-remote-gosh bash gosh_sync.sh
